version: '3.3'

services:
  test-geth:
    container_name: test-geth
    image: ethereum/client-go
    entrypoint: ""
    command: /shared/init_and_start.sh
    volumes:
      - ./shared:/shared

networks:
  weave:
    external:
      name: weave