version: '3.3'

services:
  test-geth:
    container_name: test-geth
    image: ethereum/client-go
    command: --dev --rpc --rpccorsdomain="*" --rpcapi "admin,debug,miner,shh,txpool,personal,eth,net,web3" --rpcaddr "0.0.0.0" --ws  --wsorigins="*" --wsaddr="0.0.0.0" --wsapi "personal,eth,net,web3"

networks:
  weave:
    external:
      name: weave