version: '3.3'

services:
  test-geth:
    container_name: test-geth
    image: ethereum/client-go:v1.7.3
    entrypoint: ""
    command: /shared/init_and_start.sh
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - ./shared:/shared

networks:
  weave:
    external:
      name: weave